name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      # TEST_USER: "testuser"
      TEST_EMAIL: "deepanshu@gmail.com"
      TEST_PASSWORD: "deepanshu@gmail.com"
      TEST_HOSP_NAME: "Max Hospital"
      TEST_HOSP_ADDRESS: "Delhi"
      MONGO_URI: "mongodb://localhost:27017/5510g"
      JWT_SECRET: "abcs1234"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test